### PR TITLE
Friction and ramp changes

### PR DESCRIPTION
**Pull request by shyperson0**
Made friction to be closer to quake, extended the parameters in move_ground()'s move_and_slide_with_snap() to behave better with slopes/ramps.

Some typing issues in comments fixed.

### CODE REVIEW

**Comment by shyperson0** [comment]
#2 gets fixed by this PR

**Comment by axel37** [comment]
Well, I didn't expect this, thank you !

Would that make b5b9a5a8b7f5b2308b10cf8052d125b8f452fdb8 obsolete ? *(I haven't worked on this project for a while, so you would probably know better than me !*)

**Comment by shyperson0** [comment]
Yes it would, what is done in [b5b9a5a](https://github.com/axel37/godot-quake-movement/commit/b5b9a5a8b7f5b2308b10cf8052d125b8f452fdb8) is exactly the same that move and slide already does with the extra arguments.

**Review by axel37 — APPROVED** [review]

**Comment by axel37** [comment]
Alright, everything seems good to me.

Thank you, that's very appreciated !

**Pull request merged**
